<?php namespace App\Http\Requests;

use App\Http\Requests;

class CreateFileRequest extends Request {

    public function authorize(){
        return true;
    }

    public function rules(){
        return
            [
            'title' => 'required',
                'description' => 'required',
                'file' => 'required|max:90000',
            ];
    }

    public function response(array $errors)
    {
        //return parent::response($errors); // TODO: Change the autogenerated stub

          return response()->json(['message' => $errors, 'code' => 422], 422);
    }

}